import { beforeEach, describe, expect, it } from 'vitest'
import type { ActiveStreamMeta, LogLineEvent } from '../types/log'
import { resetLogStoreForTests, useLogStore } from '../stores/logStore'

const meta = (streamId = 's1'): ActiveStreamMeta => ({ streamId, sourceId: 'src', sourceType: 'info', namespace: 'ns', pod: 'pod', container: 'app', filePath: '/x' })
const event = (streamId = 's1', raw = '{"message":"hello"}'): LogLineEvent => ({ streamId, sourceType: 'info', raw, receivedAt: 1 })

describe('logStore', () => {
  beforeEach(() => resetLogStoreForTests())
  it('clear empties buffer and visible list but not id or auto-scroll', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event()); useLogStore.getState().setAutoScrollEnabled(false); useLogStore.getState().clear(); const n = useLogStore.getState(); expect(n.rows).toHaveLength(0); expect(n.visibleRows).toHaveLength(0); expect(n.nextLineId).toBe(2); expect(n.autoScrollEnabled).toBe(false) })
  it('pause buffers but freezes visible list then resume applies grep', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event('s1','{"message":"first"}')); s.pause(); useLogStore.getState().appendLine(event('s1','{"message":"second"}')); useLogStore.getState().setGrepQuery('second'); expect(useLogStore.getState().rows).toHaveLength(2); expect(useLogStore.getState().visibleRows).toHaveLength(1); useLogStore.getState().resume(); expect(useLogStore.getState().visibleRows.map(r=>r.summary)).toEqual(['second']) })
  it('stale streamId event is ignored', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.appendLine(event('old')); expect(useLogStore.getState().rows).toHaveLength(0) })
  it('keeps lines from multiple active streams', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.prepareStarting({ ...meta('s2'), pod: 'pod-2', sourceId: 'src2' }); s.markRunning('s1'); s.markRunning('s2'); s.appendLine(event('s1','{"message":"one"}')); s.appendLine(event('s2','{"message":"two"}')); expect(useLogStore.getState().rows.map(r=>[r.streamId, r.pod, r.summary])).toEqual([['s1','pod','one'], ['s2','pod-2','two']]) })
  it('uses bufferLimit and tracks drops', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.setBufferLimit(2); s.appendLine(event('s1','{"message":"1"}')); s.appendLine(event('s1','{"message":"2"}')); s.appendLine(event('s1','{"message":"3"}')); expect(useLogStore.getState().rows.map(r=>r.summary)).toEqual(['2','3']); expect(useLogStore.getState().totalDroppedCount).toBe(1) })
  it('setBufferLimit trims and counts paused drops', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event('s1','{"message":"1"}')); s.appendLine(event('s1','{"message":"2"}')); s.pause(); useLogStore.getState().setBufferLimit(1); expect(useLogStore.getState().rows.map(r=>r.summary)).toEqual(['2']); expect(useLogStore.getState().totalDroppedCount).toBe(1); expect(useLogStore.getState().droppedWhilePaused).toBe(1) })
  it('start/running/stopping/reject semantics are streamId safe', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.markRunning('s1'); s.markStopping('other'); expect(useLogStore.getState().streamStatus).toBe('running'); s.markStartRejected('other', new Error('x')); expect(useLogStore.getState().activeStreamId).toBe('s1'); s.markStopping('s1'); expect(useLogStore.getState().streamStatus).toBe('stopping') })
  it('exit semantics distinguish requestedStop and runtime errors', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.markStopped('s1'); expect(useLogStore.getState().streamStatus).toBe('stopped'); s.prepareStarting(meta('s2')); s.markError('s2','failed'); expect(useLogStore.getState().streamStatus).toBe('error') })
  it('keeps remaining streams running when one active stream fails', () => { const s = useLogStore.getState(); s.prepareStarting(meta('info')); s.prepareStarting({ ...meta('access'), sourceType: 'access', sourceId: 'src-access' }); s.markRunning('info'); s.markRunning('access'); s.markError('access', 'tail failed'); const state = useLogStore.getState(); expect(state.activeStreamIds).toEqual(['info']); expect(state.streamStatus).toBe('running'); expect(state.errorMessage).toBe('tail failed') })
  it('groups Java stacktrace continuation lines into the previous row', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event('s1','{"message":"RuntimeException: boom"}')); s.appendLine(event('s1','    at com.example.App.run(App.java:1)')); const state = useLogStore.getState(); expect(state.rows).toHaveLength(1); expect(state.rows[0].isStacktrace).toBe(true); expect(state.rows[0].raw).toContain('App.java:1'); state.setGrepQuery('is:stacktrace'); expect(useLogStore.getState().visibleRows).toHaveLength(1) })
  it('grep regex mode refilters existing and new rows', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event('s1','{"message":"HTTP 200"}')); s.appendLine(event('s1','{"message":"HTTP 500"}')); s.setGrepQuery('http\\s+5\\d\\d'); expect(useLogStore.getState().visibleRows).toHaveLength(0); useLogStore.getState().setGrepMode('regex'); expect(useLogStore.getState().visibleRows.map(r=>r.summary)).toEqual(['HTTP 500']); useLogStore.getState().appendLine(event('s1','{"message":"HTTP 503"}')); expect(useLogStore.getState().visibleRows.map(r=>r.summary)).toEqual(['HTTP 500','HTTP 503']) })
  it('autoScrollEnabled defaults true and toggles independently', () => { expect(useLogStore.getState().autoScrollEnabled).toBe(true); useLogStore.getState().setAutoScrollEnabled(false); expect(useLogStore.getState().streamStatus).toBe('idle') })
  it('appendLines appends a batch from active streams in order', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.appendLines([event('s1', '{"message":"one"}'), event('s1', '{"message":"two"}')]); expect(useLogStore.getState().rows.map((r) => r.summary)).toEqual(['one', 'two']) })
  it('appendLines ignores stale stream lines but keeps active stream lines without consuming ids', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.appendLines([event('old', '{"message":"old"}'), event('s1', '{"message":"new"}')]); const state = useLogStore.getState(); expect(state.rows.map((r) => [r.id, r.summary])).toEqual([[1, 'new']]); expect(state.nextLineId).toBe(2) })
  it('appendLines applies buffer limit and total dropped count', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.setBufferLimit(2); s.appendLines([event('s1', '{"message":"1"}'), event('s1', '{"message":"2"}'), event('s1', '{"message":"3"}')]); expect(useLogStore.getState().rows.map((r) => r.summary)).toEqual(['2', '3']); expect(useLogStore.getState().totalDroppedCount).toBe(1) })
  it('appendLines respects pause behavior', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLine(event('s1', '{"message":"visible"}')); s.pause(); s.appendLines([event('s1', '{"message":"hidden"}')]); expect(useLogStore.getState().visibleRows.map((r) => r.summary)).toEqual(['visible']); useLogStore.getState().resume(); expect(useLogStore.getState().visibleRows.map((r) => r.summary)).toEqual(['visible', 'hidden']) })
  it('appendLines respects regex grep mode', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.setGrepQuery('HTTP\\s+5\\d\\d'); s.setGrepMode('regex'); s.appendLines([event('s1', '{"message":"HTTP 200"}'), event('s1', '{"message":"HTTP 503"}')]); expect(useLogStore.getState().visibleRows.map((r) => r.summary)).toEqual(['HTTP 503']) })
  it('stacktrace continuation consumes an id even when grouped', () => { const s = useLogStore.getState(); s.prepareStarting(meta()); s.appendLines([event('s1', '{"message":"RuntimeException: boom"}'), event('s1', '    at com.example.App.run(App.java:1)')]); const state = useLogStore.getState(); expect(state.rows).toHaveLength(1); expect(state.nextLineId).toBe(3) })
  it('records stderr per active stream and ignores stale streams', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.recordStderr('old', 'old'); s.recordStderr('s1', 'err'); expect(useLogStore.getState().latestStderr).toBe('err'); expect(useLogStore.getState().stderrByStream.s1).toEqual(['err']); expect(useLogStore.getState().stderrByStream.old).toBeUndefined() })
  it('caps stderr history per stream at 20 lines', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); for (let i = 0; i < 25; i += 1) s.recordStderr('s1', `err-${i}`); expect(useLogStore.getState().stderrByStream.s1).toHaveLength(20); expect(useLogStore.getState().stderrByStream.s1[0]).toBe('err-5') })
  it('replaceStreamForReconnect swaps ids while preserving rows and error message', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.appendLine(event('s1', '{"message":"keep"}')); s.markError(undefined, 'previous'); s.replaceStreamForReconnect('s1', { ...meta('s2'), pod: 'pod-2' }); const state = useLogStore.getState(); expect(state.activeStreamIds).toEqual(['s2']); expect(state.activeStreamMetas.s1).toBeUndefined(); expect(state.rows.map((r) => r.summary)).toEqual(['keep']); expect(state.errorMessage).toBe('previous'); expect(state.streamStatus).toBe('starting') })
  it('resetForSelectionChange starts a fresh visible session', () => { const s = useLogStore.getState(); s.prepareStarting(meta('old')); s.appendLine(event('old', '{"message":"old-1"}')); s.appendLine(event('old', '{"message":"old-2"}')); s.pause(); s.setBufferLimit(1); s.resetForSelectionChange(); const reset = useLogStore.getState(); expect(reset.viewerPaused).toBe(false); expect(reset.droppedWhilePaused).toBe(0); expect(reset.totalDroppedCount).toBe(0); reset.prepareStarting(meta('new')); reset.appendLine(event('new', '{"message":"new"}')); expect(useLogStore.getState().visibleRows.map((r) => r.summary)).toEqual(['new']) })
  it('groups stacktrace continuations with same stream even when another stream interleaves', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.prepareStarting({ ...meta('s2'), sourceId: 'src2', pod: 'pod-2' }); s.appendLines([event('s1', '{"message":"RuntimeException: boom"}'), event('s2', '{"message":"other"}'), event('s1', '    at com.example.App.run(App.java:1)')]); const state = useLogStore.getState(); const s1Row = state.rows.find((r) => r.streamId === 's1'); expect(s1Row?.raw).toContain('App.java:1'); state.setGrepQuery('is:stacktrace'); expect(useLogStore.getState().visibleRows.some((r) => r.streamId === 's1')).toBe(true) })
  it('does not group stacktrace continuations beyond row horizon', () => { const s = useLogStore.getState(); s.prepareStarting(meta('s1')); s.appendLine(event('s1', '{"message":"RuntimeException: old"}')); for (let i = 0; i < 201; i += 1) s.appendLine(event('s1', `{"message":"filler ${i}"}`)); s.appendLine(event('s1', '    at com.example.App.run(App.java:1)')); const state = useLogStore.getState(); expect(state.rows.at(-1)?.raw).toBe('    at com.example.App.run(App.java:1)') })
})
